package com.tunlezah.dashcam.map

/** A downloadable offline map region. */
data class MapRegion(
    val id: String,
    val label: String,
    /** Measured archive size (docs/offline-maps.md), shown before download. */
    val approxSizeMb: Int,
    val url: String,
)

/**
 * Built-in Australian offline map regions (brief §29: "allow the user to
 * download an Australian map/regions for offline use").
 *
 * The data files are PMTiles extracts of the Protomaps daily OpenStreetMap
 * build, generated by this repository's `map-data` GitHub Actions workflow
 * and hosted as GitHub Release assets — no third-party server, no API key,
 * fully offline after download. Sizes were measured from the actual extracts.
 * Data © OpenStreetMap contributors (ODbL).
 */
object MapRegionCatalog {

    const val RELEASE_TAG = "map-data-v1"
    private const val BASE =
        "https://github.com/tunlezah/DashCam/releases/download/$RELEASE_TAG"

    val regions: List<MapRegion> = listOf(
        MapRegion("au-nsw-act", "New South Wales + ACT", 364, "$BASE/au-nsw-act.pmtiles"),
        MapRegion("au-vic", "Victoria", 239, "$BASE/au-vic.pmtiles"),
        MapRegion("au-qld", "Queensland", 261, "$BASE/au-qld.pmtiles"),
        MapRegion("au-sa", "South Australia", 98, "$BASE/au-sa.pmtiles"),
        MapRegion("au-wa", "Western Australia", 184, "$BASE/au-wa.pmtiles"),
        MapRegion("au-tas", "Tasmania", 58, "$BASE/au-tas.pmtiles"),
        MapRegion("au-nt", "Northern Territory", 47, "$BASE/au-nt.pmtiles"),
        MapRegion("au-all", "All Australia (lower detail)", 242, "$BASE/au-all.pmtiles"),
    )
}
